pouches:
  common:

    # The display name of the Pouch
    name: '&r&6&lCommon Pouch'

    # The material of your Pouch
    material: 'ender_chest'

    # Current Animations
    # NONE, TITLE, ACTIONBAR, BOSSBAR, RANDOM
    animation: NONE

    # The minimum amount of money a Player can receive.
    min: 100

    # The maximum amount of money a Player can receive.
    max: 500

    # Current Currencies
    # BEDROCKECONOMY, XP
    currency: BEDROCKECONOMY

    # The Pouch's lore.
    lore:
      - ''
      - '&r&7Open this pouch to receive money!'
      - ''
      - '&r&7Range: &6$100 &7- &6$500'
  uncommon:
    name: '&r&e&lUncommon Pouch'
    material: 'ender_chest'
    animation: ACTIONBAR
    min: 500
    max: 1000
    currency: BEDROCKECONOMY
    lore:
      - ''
      - '&r&7Open this Pouch to receive Money!'
      - ''
      - '&r&7Range: &e$500 &7- &e$1000'
  rare:
    name: '&r&3&lRare Pouch'
    material: 'ender_chest'
    animation: BOSSBAR
    min: 1000
    max: 1500
    currency: BEDROCKECONOMY
    lore:
      - ''
      - '&r&7Open this Pouch to receive Money!'
      - ''
      - '&r&7Range: &3$1000 &7- &3$1500'
  legendary:
    name: '&r&a&lLegendary Pouch'
    material: 'ender_chest'
    animation: 'TITLE'
    min: 2000
    max: 2500
    currency: BEDROCKECONOMY
    lore:
      - ''
      - '&r&7Open this Pouch to receive Money!'
      - ''
      - '&r&7Range: &a$1500 &7- &a$2000'

animations:

  # None Animation Settings
  none:

    # How long would you like players to be able to redeem Pouches with this Animation? (In seconds)
    cooldown: 0

    # Should this animation also send the Prize Message to the player?
    show_prize_message: true

    # What sound should be played? (Empty for no sound)
    sound: ''

  # Title Animation Settings
  title:

    # How fast should the title progress be? (In ticks, 20 ticks = 1 Second)
    ticks: 10

    # How long would you like players to be able to redeem Pouches with this Animation? (In seconds)
    cooldown: 3

    # What sound should be played? (Empty for no sound)
    start_sound: ''

    # What sound should be played? (Empty for no sound)
    end_sound: ''

    # Should the title Animation also send the Prize Message to the player?
    show_prize_message: true

    # The color code that the Prefix will be displayed with
    prefix_color: '&a'

    # The color code that the Suffix will be displayed with
    suffix_color: '&a'

    # The color code that the Amount will be displayed with
    reveal_color: '&a'

    # The color code that the Obfuscated Digits will be displayed with
    obfuscate_color: '&b'

    # The Title Message
    title: '{reward}'

    # The Subtitle Message
    subtitle: '&r&fOpening Pouch...'

  # Actionbar Animation Settings
  actionbar:

    # How fast should the actionbar progress be? (In ticks, 20 ticks = 1 Second)
    ticks: 10

    # How long would you like players to be able to redeem Pouches with this Animation? (In seconds)
    cooldown: 3

    # What sound should be played? (Empty for no sound)
    start_sound: ''

    # What sound should be played? (Empty for no sound)
    end_sound: ''

    # Should the actionbar Animation also send the Prize Message to the player?
    show_prize_message: false

    # The color code that the Prefix will be displayed with
    prefix_color: '&a'

    # The color code that the Suffix will be displayed with
    suffix_color: '&a'

    # The color code that the Amount will be displayed with
    reveal_color: '&a'

    # The color code that the Obfuscated Digits will be displayed with
    obfuscate_color: '&b'

    # Should the amount be formatted? (ie: 1,523,640)
    format: true

    # Should the Amount start getting shown Right to Left?
    right_to_left: true

    # The Actionbar Message
    actionbar: '&fYou have earned {reward}'

  # BossBar Animation Settings
  bossbar:

    # How fast should the bossbar progress be? (In ticks, 20 ticks = 1 Second)
    ticks: 10

    # How long would you like players to be able to redeem Pouches with this Animation? (In seconds)
    cooldown: 6

    # What sound should be played? (Empty for no sound)
    start_sound: ''

    # What sound should be played? (Empty for no sound)
    end_sound: ''

    # Should the bossbar Animation also send the Prize Message to the player?
    show_prize_message: false

    # The color code that the Prefix will be displayed with
    prefix_color: '&a'

    # The color code that the Suffix will be displayed with
    suffix_color: '&a'

    # The color code that the Amount will be displayed with
    reveal_color: '&a'

    # The color code that the Obfuscated Digits will be displayed with
    obfuscate_color: '&b'

    # Should the amount be formatted? (ie: 1,523,640)
    format: true

    # Should the comma be shown?
    reveal_comma: false

    # The BossBar Message
    text: '&fYour prize is {reward}'

  # Random Animation Settings
  random:

    # How long would you like players to be able to redeem Pouches with this Animation? (In seconds)
    cooldown: 6

    # Should the bossbar Animation also send the Prize Message to the player?
    show_prize_message: true
